Controllers/UnidentifiedMapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using System.Xml.Linq;
using System.Xml.Serialization;
using WruntsTools.Models;

namespace WruntsTools.Controllers
{
    public class UnidentifiedMapController : Controller
    {
        public ActionResult Index()
        {
            MapAffixModel mam = new MapAffixModel();

            Session["mam"] = mam;

            return View(mam);
        }

        [HttpPost]
        public ActionResult AddAffix(string affixName)
        {
            MapAffixModel mam = new MapAffixModel();

            mam = (MapAffixModel)Session["mam"];

            if (!mam.HasAffix(affixName))
            {
                Affix aff = mam.AffixLst.Where(a => a.Name == affixName).FirstOrDefault();

                if (aff.Type == "Prefix")
                {
                    mam.IncludedPrefixLst.Add(aff);
                }
                else
                {
                    mam.IncludedSuffixLst.Add(aff);
                }
            }

            mam.UpdateRemainingQuantity();

            Session["mam"] = mam;

            return Json(mam);
        }

        [HttpPost]
        public ActionResult RemoveAffix(string affixName)
        {
            MapAffixModel mam = new MapAffixModel();

            mam = (MapAffixModel)Session["mam"];

            if (mam.HasAffix(affixName))
            {
                Affix aff = mam.AffixLst.Where(a => a.Name == affixName).FirstOrDefault();

                if (aff.Type == "Prefix")
                {
                    mam.IncludedPrefixLst.Remove(aff);
                }
                else
                {
                    mam.IncludedSuffixLst.Remove(aff);
                }
            }

            mam.UpdateRemainingQuantity();

            Session["mam"] = mam;

            return Json(mam);
        }

        [HttpPost]
        public ActionResult UpdateProperty(string PropName, string Value)
        {
            MapAffixModel mam = new MapAffixModel();

            mam = (MapAffixModel)Session["mam"];

            switch (PropName)
            {
                case "Rarity":
                    mam.GetType().GetProperty(PropName).SetValue(mam, (Value == "Rare" ? ItemRarity.Rare : ItemRarity.Magic), null);
                    break;

                case "Quality": case "Bonuses": case "Quantity":
                    mam.GetType().GetProperty(PropName).SetValue(mam, Int32.Parse(Value), null);
                    break;
            }

            mam.UpdateRemainingQuantity();

            Session["mam"] = mam;

            return Json(mam);
        }

        [HttpGet]
        public ActionResult GetPossibleAffixes()
        {
            MapAffixModel mam = (MapAffixModel)Session["mam"];

            mam.UpdateRemainingQuantity();

            return Json(mam.PossibleAffixes, JsonRequestBehavior.AllowGet);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/x-icon" href="http://wrunt.azurewebsites.net/favicon.ico?id=1" />
    <link rel="icon" type="image/x-icon" href="http://wrunt.azurewebsites.net/favicon.ico?id=1" />
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <title>@ViewBag.Title - Wrunt's Tools</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("Wrunt's Tools", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Unidenfitied Map Planner", "Index", "UnidentifiedMap")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>